### ISSUE TITLE
TypeError: an integer is required (got type Reader)

### ISSUE THREAD

**Issue by meeftah** [zishor/yolo-python-rtsp#2]
Hi, I got an error:
`Traceback (most recent call last):
  File "yolo_opencv.py", line 184, in <module>
    processvideo(reader)
  File "yolo_opencv.py", line 131, in processvideo
    cap = cv2.VideoCapture(file)
TypeError: an integer is required (got type Reader)`

is there something that I should do?

**Comment by foschmitz** [comment]
Hi, thanks for the hint. Updated to imagio-ffmpeg and adjusted the readme. Also tested with rtsp, still working fine.
